### ISSUE TITLE
Domain registration expired for virgoagent.com :(

### ISSUE THREAD

**Issue by imlucas** [virgo-agent-toolkit/virgo-agent-toolkit.github.io#11]
<img width="1280" alt="screen shot 2015-08-26 at 1 04 26 pm" src="https://cloud.githubusercontent.com/assets/23074/9500374/11eb2c7e-4bf3-11e5-8cd6-22c1cdabbea5.png">

**Comment by eddywashere** [comment]
renewed. might take some time to propagate.
